language: node_js

services:
  - docker

node_js:
  - "8.9.4"

branches:
  only:
    - master
    - recette

env:
  global:
    secure: $GH_TOKEN

before_script:
  - sudo -- sh -c "echo '127.0.0.1 mysql' >> /etc/hosts"


script:
  - git checkout master
  - npm install
  - export NODE_ENV=test
  - docker run --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_USER=mimir02 -e MYSQL_PASSWORD=virgule02 -e MYSQL_DATABASE=todosappdb -d mysql:5.6
  - sleep 40 
  - npm start && npm test
  - git add --all
  - git rm .travis.yml
  - git commit -m "Commit from travis from master branch"
  - git push --force https://$GH_TOKEN@github.com/mimir02/nodeDevOpsAPI.git master:docker-prod

notifications:
  email:
    on_failure: change
    on_success: change